### ISSUE TITLE
Alfred Preferences Not Found At Location

### ISSUE THREAD

**Issue by rikmatena** [SamVerschueren/resolve-alfred-prefs#2]
@SamVerschueren hi, thanks for your work :)
I'm opening this issue that I encountered trying to install the https://github.com/adriantoine/alfred-asana workflow. Someone else (@dilanshah) opened it there, and I'm getting the exact same problem, so I'll copy-paste their report from https://github.com/adriantoine/alfred-asana/issues/4:

```
In an attempt to use this, I'm running into the following bug.

Command:
Dilans-MBP-2:~ dilanshah$ sudo npm install -g alfred-asana

Result

alfred-asana@1.2.0 postinstall /usr/local/lib/node_modules/alfred-asana
alfred-link

Error: Alfred preferences not found at location /Users/dilanshah/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist
at pathExists.then.exists (/usr/local/lib/node_modules/alfred-asana/node_modules/resolve-alfred-prefs/index.js:15:10)

Would you mind taking a look at how I can maybe edit the path that the installer is checking?
```

**Comment by SamVerschueren** [comment]
You are 100% sure you have Alfred 3 installed? If this is the case, can you find out where you `Alfred-Preferences-3.plist` is stored?

This library only supports Alfred 3, so it doesn't work otherwise.

Offtopic: It's a bad idea to install packages globally with `sudo`. See the [fixing npm permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions) permissions. Installing with `sudo` allows malicious packages to run as super user, I think we all know what this means ;).

**Comment by rikmatena** [comment]
Thanks @SamVerschueren. The issue was solved by following your offtopic advice :) I reinstalled npm and changed its default directory (option 2 in [fixing npm permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions)). After that, I no longer had issues installing `alfred-asana`.

**Comment by SamVerschueren** [comment]
Good to know. 

@sindresorhus maybe we should use `sudo-block` for Alfred workflows, what do you think?

**Comment by sindresorhus** [comment]
Yes, let's do it.

**Comment by megaroeny** [comment]
Please see my comment/issue related to not using the default location for Preferences. In my case, they're in my Dropbox folder:

https://github.com/SamVerschueren/alfred-link/pull/20#issuecomment-472024948

**Comment by sonicdoe** [comment]
@jaminroe How are you installing alfred-figma? Are you perhaps using `sudo npm install --global alfred-figma`?

**Comment by megaroeny** [comment]
@sonicdoe I am, yes! Sorry, I'm very newbie to npm, console, etc. Been a while too last I used it. The main issue will be solved if they update to the latest version of `alfy`. Think they just did, but not home to try it. 😊
